kind: Secret
apiVersion: v1
metadata:   
  name: secret 
  namespace: airpollution 
type: Opaque
stringData: 
  mongo-username: admin
  mongo-password: admin123
  mongo-uri: mongodb://admin:admin123@mongo-service:27017/PollutionDataSet?authSource=admin
